### ISSUE TITLE
Superfluous parameter access when using service persistence

### ISSUE THREAD

**Issue by schmidf** [tiqi-group/pydase#13]
When using service persistence, pydase reads parameters many times instead of only once. Example:

```python

from pydase import DataService, Server

class Device(DataService):
    _current = 0.0

    @property
    def current(self):
        # run code to get current
        result = self._current
        print(f"Reading current. Result: {result}")
        return result

    @current.setter
    def current(self, value):
        # run code to set current
        print(f"Set current to {value}")
        self._current = value

if __name__ == "__main__":
    service = Device("device_state.json")
    Server(service).run()
```

`current` is set to 10 using the web interface. Output after stopping and restarting the script:

```
Reading current. Result: 0.0
Reading current. Result: 0.0
Reading current. Result: 0.0
Reading current. Result: 0.0
Reading current. Result: 0.0
Set current to 10.0
Reading current. Result: 10.0
```

A similar issue appears when changing the value in the web interface:
```
Reading current. Result: 10.0
Reading current. Result: 10.0
Reading current. Result: 10.0
Set current to 9.0
Reading current. Result: 9.0
```

In the lab, each of the reads would lead to a hardware access which can be very slow. The number of parameter reads and writes should be kept to a minimum.

**Comment by mosmuell** [comment]
So, I can remove the first three property accesses. The fourth one should probably not be removed. It accesses the value of the property to push the update notification to the frontend. As the setter can be very complicated, and the value passed to the setter does not have to be the value the property getter returns, you will have to access the property to get the correct value.

**Comment by mosmuell** [comment]
I haven't looked at service persistence yet, sorry about that. But I reckon that this is not a problem as this will only happen when the service is started?

**Comment by mosmuell** [comment]
The first access when starting the server is in the `_set_start_and_stop_for_async_methods` method, which creates start- and stop-methods for async methods. This function inspects the members of the service class using `inspect.getmembers` which apparently accesses the properties.

The second access when loading the state from a json file corresponds to a serialization of the class. With this, it checks if the serialization of the current service contains the entries in the json file.
