### ISSUE TITLE
Spin box buttons not working

### ISSUE THREAD

**Issue by schmidf** [tiqi-group/pydase#14]
I am using the code example from the README file. When clicking the + or - buttons of the spin boxes, nothing happens.

**Comment by mosmuell** [comment]
I have not yet implemented this "feature" as it is not really clear what the buttons should do. Should they only in-/decrease the leftmost digit by one? Then they would be rather pointless. Should they increase some other digit within the number? How should the user tell the number component which digit this is? The user could use the up- and down-arrow keys to do the same on the PC.

**Comment by schmidf** [comment]
Maybe it would be best to simply remove the buttons. I don't think we typically use them in the lab.

Am 14. September 2023 09:10:01 MESZ schrieb "Mose Müller" ***@***.***>:
