### ISSUE TITLE
Defining task without autostart fails

### ISSUE THREAD

**Issue by lmaisenbacherberkeley** [tiqi-group/pydase#158]
## Describe the bug
Using pydase 0.10.1, defining as task with the `@task` decorator without autostart (`@task()` or `@task(autostart=False)`) leads to failure to start server.

## To Reproduce
```python
import asyncio

import pydase
from pydase.task.decorator import task

class MyService(pydase.DataService):
    @task(autostart=False)
    async def my_task(self) -> None:
        while True:
            # Perform some periodic work
            await asyncio.sleep(1)

if __name__ == "__main__":
    service = MyService()
    pydase.Server(service=service).run()
```

## Expected behaviour
Should generate frontend element to start/stop task.

## Screenshot/Video
![image](https://github.com/user-attachments/assets/08a6edf0-4f1d-4a83-b481-684ca4a666bc)

## Additional context
Defining the task with autostart (`@task(autostart=True)`) starts the server successfully, generates the start/stop elements, and starts the task.

**Comment by mosmuell** [comment]
Thanks for the bug report! I will be looking into this shortly.

**Comment by lmaisenbacherberkeley** [comment]
Confirmed that this is now fixed - thank you for taking care of this so quickly!

**Comment by mosmuell** [comment]
My pleasure. Thanks for the feedback!
