### ISSUE TITLE
asyncio loop conflicts when initializing a pydase client inside a pydase server

### ISSUE THREAD

**Issue by lmaisenbacherberkeley** [tiqi-group/pydase#170]
## Describe the bug
I would like start a pydase client inside a pydase server (the secondary server), with the client connecting to another pydase server (the primary server). I've used this successfully in pydase 0.7.4 to implement a PID controller inside the secondary server, with the input and output of the controller from the primary server(s).
However, with pydase 0.10.3 and on Windows, I run into issues related to the asyncio loops used by both the pydase client and server; see code and error below.

## To Reproduce
The primary server (localhost:8001) is defined in "simple_task.py":
```python
import asyncio

from pydase import DataService, Server
from pydase.task.decorator import task

class MyService(DataService):

    def __init__(self):
        super().__init__()
        self.data : int = 0

    @task(autostart=True)
    async def my_task(self) -> None:
        while True:
            # Perform some periodic work
            self.data += 1
            await asyncio.sleep(1)

if __name__ == "__main__":
    service = MyService()
    Server(service=service, web_port=8001).run()
```

The secondary server (localhost:8002) containing the client is defined in "server_w_client.py":
```python
import asyncio

from pydase.task.decorator import task
from pydase import DataService, Server, Client
from pydase.utils.decorators import frontend

class MyService(DataService):

    def __init__(self):
        super().__init__()
        self._client_proxy = None
        self.data : int = 0

    @frontend
    def connect(self):
        """Connect to input/output."""
        client = Client(
            url=f'ws://localhost:8001',
            block_until_connected=True)
        self._client_proxy = client.proxy

    @task(autostart=False)
    async def my_task(self) -> None:
        while True:
            # Perform some periodic work
            if self._client_proxy is not None:
                self.data = self._client_proxy.data
            await asyncio.sleep(1)

if __name__ == "__main__":
    service = MyService()
    Server(service=service, web_port=8002).run()
```

Run the primary server, then the secondary server. Connect to GUI of the secondary server at "localhost:8002". Click the "Connect" button to initialize the client connecting to the primary server. On Windows and pydase 0.10.3, this gives the error(s):

```
Exception in thread Thread-1 (asyncio_loop_thread):
Traceback (most recent call last):
  File "C:\Users\Lothar\anaconda3\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Lothar\anaconda3\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Lothar\Coding\unitrap-pydase-apps\venv\pydase0.1\Lib\site-packages\pydase\client\client.py", line 36, in asyncio_loop_thread
    loop.run_forever()
  File "C:\Users\Lothar\anaconda3\Lib\asyncio\windows_events.py", line 319, in run_forever
    assert self._self_reading_future is None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

## Expected behaviour
Expected or ideal behavior would be that the second server can start a client connecting to the first server.

## Possible solution
In "client/client.py/Client", instead of
```
if not current_event_loop_exists():
    self._loop = asyncio.new_event_loop()
    asyncio.set_event_loop(self._loop)
else:
    self._loop = asyncio.get_event_loop()
```

just using the first case

```
self._loop = asyncio.new_event_loop()
asyncio.set_event_loop(self._loop)
```

will lead to the client being run in a new event loop, which does not conflict with the server.

There are probably reasons against this, and I'm certainly not an expert in asyncio, so a generally accepted solution that allows the above functionality would be great.

**Comment by mosmuell** [comment]
Thanks for the bug report! Interestingly, I have already implemented your solution in #165 for another use case. Can you confirm the bug is fixed when updating to pydase `v0.10.5`?

**Comment by lmaisenbacherberkeley** [comment]
Testing with `v0.10.6`, this issue has indeed been resolved - great, thanks!

I did notice that this warning is now emitted when initializing the client (e.g., by running the above code, but this also happens in a simple script just involving a client and no secondary server):
```
WARNING  | pydase.data_service.data_service:__warn_if_not_observable:73 - Class 'method' does not inherit from DataService. This may lead to unexpected behaviour!
```

**Comment by mosmuell** [comment]
Cool.
Ah, thanks for the feedback. I thought I fixed that.
