### ISSUE TITLE
Logging level

### ISSUE THREAD

**Issue by carmelom** [tiqi-group/pydase#2]
Let the user choose the logging level. which at the moment defaults to DEBUG. Either via `logging` or `loguru` or with some pydase function.

**Comment by mosmuell** [comment]
This is now possible in the newest commit (see [here (if `docs` is not merged yet)](https://github.com/tiqi-group/pydase/tree/docs#changing-the-log-level) or [here](https://github.com/tiqi-group/pydase#changing-the-log-level))
