### ISSUE TITLE
Issue: Pydase checks if protected variables inherit from DataService

### ISSUE THREAD

**Issue by marti-m** [tiqi-group/pydase#24]
See title. Reduce the scope to public variables (or whatever these are called in Python)
![image](https://github.com/tiqi-group/pydase/assets/98454601/222e6304-2b53-44bc-8ef2-546187d517fe)

**Comment by mosmuell** [comment]
```python
class ProprietaryClass:
    pass


class WarningTest(DataService):
    _display = ProprietaryClass()


if __name__ == "__main__":
    service = WarningTest()
```

doesn't throw this warning anymore
