### ISSUE TITLE
Wrong types for non-standard saved variables

### ISSUE THREAD

**Issue by Iucimhub** [tiqi-group/pydase#49]
**Is your feature request related to a problem? Please describe.**
At the startup of the pydase app, internally the variables are set to whatever values have been saved previously. However, the type of non-standard type variable are wrong, in particular:

pydase.units.Quantity: set as dict
pydase.components.ColouredEnum: set as str

This becomes problematic for example if we would like to check if the variable is in a specific state:

`
self.lock_status: LockStatus = LockStatus.LOCKED
`
And later we might want to check it:
`
if self.lock_status == LockStatus.LOCKED
`
This will return false if self.lock_status has been set to the string "LOCKED"

**Describe the solution you'd like**
Make sure the variables are set in the original type format.

**Comment by mosmuell** [comment]
Thanks for the issue. I got an assertion error when trying to load ColouredEnums from a settings file. That should be fixed now.
However, I cannot produce an issue with a Quantity. Could you provide me with an example for a Quantity? This is a working example:

```python
import pydase
import pydase.units as u


class Test(pydase.DataService):
    def __init__(self):
        self._unit: u.Quantity = 1 * u.units.A
        super().__init__(filename="settings.json")

    @property
    def some_unit(self) -> u.Quantity:
        return self._unit

    @some_unit.setter
    def some_unit(self, value) -> None:
        self._unit = value


if __name__ == "__main__":
    service = Test()
    pydase.Server(service).run()
```

**Comment by Iucimhub** [comment]
What if you try accessing the magnitude of the value in the setter? This can be necessary when talking to devices which expect only a number. E.g.:
```
import pydase
import pydase.units as u


class Test(pydase.DataService):
    def __init__(self):
        self._unit: u.Quantity = 1 * u.units.A
        super().__init__(filename="settings.json")

    @property
    def some_unit(self) -> u.Quantity:
        return self._unit

    @some_unit.setter
    def some_unit(self, value) -> None:
        print(f"The magnitude of the value is {value.m}")
        self._unit = value


if __name__ == "__main__":
    service = Test()
    pydase.Server(service).run()
```

**Comment by mosmuell** [comment]
I see. I would have to take care of the conversion when reading from the settings file. Thanks for pointing that out.
