### ISSUE TITLE
Problem with negative number 

### ISSUE THREAD

**Issue by Iucimhub** [tiqi-group/pydase#50]
**Is your feature request related to a problem? Please describe.**
For a variable defined as:

` etalon_factor: u.Quantity = 10 * u.units.GHz/u.units.percent`

it is impossible to type a minus sign in the corresponding form on the pydase app.

**Comment by mosmuell** [comment]
I cannot reproduce this. This example is working for me:

```python
import pydase
import pydase.units as u


class Test(pydase.DataService):
    def __init__(self):
        self.etalon_factor: u.Quantity = -10 * u.units.GHz / u.units.percent
        super().__init__(filename="settings.json")


if __name__ == "__main__":
    service = Test()
    pydase.Server(service).run()
```

I can change the values on the frontend to both positive and negative values.
