### ISSUE TITLE
Settings repo

### ISSUE THREAD

**Issue by philipleindecker** [tiqi-group/pydase#87]
Settings repo (as already discussed) → for separation between the settings and the device code (also see [Plan for Service Structure ](https://www.notion.so/itqc/Tickets-da683334cde94b1e9ee2855e9934e4d9?pvs=4#d9ee1fcf80bd482782e88a531c57e14d)
Also relevant for the repos that the Research Assistants are writing. The later it comes the more they need to rewrite afterwards.

**Comment by mosmuell** [comment]
I try to make all things configurable through the [config module](https://github.com/tiqi-group/pydase/blob/main/src/pydase/config.py). The user can set the config directory using the environment variable `$SERVICE_CONFIG_DIR` which defaults to the "config" folder in the root folder of the service. This folder is used to store the web settings. You can also use this folder to store your personal service config (access to the path is provided through `ServiceConfig().config_dir`).

If you think there are still some things missing, feel free to reopen the issue.
